### ISSUE TITLE
Need to add source for chart

### ISSUE THREAD

**Issue by franzknupfer** [epicodus-classroom/dei-curriculum#3]
Chart in https://github.com/epicodus-classroom/dei-curriculum/blob/master/dei-talks/2_recognizing_privilege.md has no source.

**Comment by franzknupfer** [comment]
Hey Brooke! The chart in the lesson above comes from slide 16 in the week 2 DEI talk. There's no attribution, though, and we should add the source to the lesson. Can you let me know the source so I can add it to the lesson? Thanks!

**Comment by kullb3rg** [comment]
It came from https://frameshiftconsulting.com/ally-skills-workshop/
Specifically the `Identifying power and privilege exercise`

**Comment by franzknupfer** [comment]
Thanks! Lesson updated to add link.
