### ISSUE TITLE
Update microaggressions lesson to use following language "student with a disability"

### ISSUE THREAD

**Issue by kullb3rg** [epicodus-classroom/dei-curriculum#6]
I found a pretty cool resource on [diability ettiquette](unitedspinal.org/pdf/DisabilityEtiquette.pdf) and they suggest referring to students with disabilities just like so, and not to say "disabled student" or "disabled person". The microaggressions lesson has at least one example of a microaggression that uses the phrase "disabled student" that should be changed.

**Comment by franzknupfer** [comment]
Yes, it should definitely be person with disability, not disabled... not sure how that got in the lesson! I'll change that now.

**Comment by franzknupfer** [comment]
Fixed!
